export const mockSettings = {
  theme: 'defaultDark',
  showDebugWindow: false,
  globalMediaHotkeys: true,
  cachePath: 'C:\\Users\\jli\\AppData\\Roaming\\Electron',
  volume: 0.93,
  seekForwardInterval: 5,
  seekBackwardInterval: 5,
  volumeFade: true,
  repeat: 'all',
  shuffle: false,
  scrollWithCurrentSong: true,
  cacheImages: true,
  cacheSongs: false,
  pollingInterval: 20,
  fadeDuration: 9,
  fadeType: 'equalPower',
  scrobble: false,
  musicFolder: {
    id: null,
    albums: true,
    artists: true,
    dashboard: false,
    search: false,
    starred: false,
  },
  gridCardSize: 200,
  playlistViewType: 'grid',
  albumViewType: 'grid',
  musicListFontSize: 13,
  musicListRowHeight: 50,
  musicListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '# (Drag/Drop)',
    },
    {
      id: 'Title',
      dataKey: 'combinedtitle',
      alignment: 'left',
      resizable: true,
      width: 273,
      label: 'Title (Combined)',
    },
    {
      id: 'Album',
      dataKey: 'album',
      alignment: 'left',
      resizable: true,
      width: 263,
      label: 'Album',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 110,
      label: 'Duration',
    },
    {
      id: 'Bitrate',
      dataKey: 'bitRate',
      alignment: 'left',
      resizable: true,
      width: 72,
      label: 'Bitrate',
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Favorite',
    },
  ],
  albumListFontSize: 14,
  albumListRowHeight: 60,
  albumListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
    },
    {
      id: 'Title',
      dataKey: 'combinedtitle',
      alignment: 'left',
      resizable: true,
      width: 457,
      label: 'Title (Combined)',
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Track Count',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 80,
      label: 'Duration',
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Favorite',
    },
  ],
  artistListFontSize: 14,
  artistListRowHeight: 60,
  artistListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
      uniqueId: 'bOCYMfNieUHtjl1XhM-GT',
    },
    {
      id: 'Art',
      dataKey: 'coverart',
      alignment: 'center',
      resizable: true,
      width: 74,
      label: 'CoverArt',
      uniqueId: '2Z8rUZi47VnlQSBfZzRk8',
    },
    {
      id: 'Name',
      dataKey: 'name',
      alignment: 'left',
      flexGrow: 5,
      label: 'Name',
      uniqueId: 'Vv_luiyR3rp5b07Szd0zd',
    },
    {
      id: 'Album Count',
      dataKey: 'albumCount',
      alignment: 'left',
      flexGrow: 1,
      label: 'Album Count',
      uniqueId: 'IScD9714XLFrQYSAFkmoL',
    },
    {
      id: 'Fav',
      dataKey: 'starred',
      alignment: 'center',
      flexGrow: 1,
      label: 'Favorite',
      uniqueId: 'eFrudHQBTnBXNuD3mL-c1',
    },
  ],
  genreListFontSize: 14,
  genreListRowHeight: 50,
  genreListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 66,
      label: '#',
      uniqueId: 'ZXNE6gsaLm0kVRyueOBHS',
    },
    {
      id: 'Name',
      dataKey: 'name',
      alignment: 'left',
      flexGrow: 5,
      label: 'Name',
      uniqueId: 'FTY1gWAjc0i6NVjim_8aZ',
    },
    {
      id: 'Album Count',
      dataKey: 'albumCount',
      alignment: 'left',
      flexGrow: 1,
      label: 'Album Count',
      uniqueId: 'oHqG0mGN_E7iLairZGnZL',
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      flexGrow: 1,
      label: 'Track Count',
      uniqueId: 'c1qxv4S5YC7YUvbOG_WJF',
    },
  ],
  playlistListFontSize: 14,
  playlistListRowHeight: 80,
  playlistListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '#',
    },
    {
      id: 'Art',
      dataKey: 'coverart',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'CoverArt',
    },
    {
      id: 'Title',
      dataKey: 'name',
      alignment: 'left',
      resizable: true,
      width: 300,
      label: 'Title',
    },
    {
      id: 'Description',
      dataKey: 'comment',
      alignment: 'left',
      resizable: true,
      width: 200,
      label: 'Description',
    },
    {
      id: 'Tracks',
      dataKey: 'songCount',
      alignment: 'center',
      resizable: true,
      width: 100,
      label: 'Track Count',
    },
    {
      id: 'Owner',
      dataKey: 'owner',
      alignment: 'left',
      resizable: true,
      width: 150,
      label: 'Owner',
    },
    {
      id: 'Modified',
      dataKey: 'changed',
      alignment: 'left',
      resizable: true,
      width: 100,
      label: 'Modified',
    },
  ],
  miniListFontSize: 14,
  miniListRowHeight: 40,
  miniListColumns: [
    {
      id: '#',
      dataKey: 'index',
      alignment: 'center',
      resizable: true,
      width: 50,
      label: '# (Drag/Drop)',
    },
    {
      id: 'Title',
      dataKey: 'title',
      alignment: 'left',
      resizable: true,
      width: 250,
      label: 'Title',
    },
    {
      id: 'Duration',
      dataKey: 'duration',
      alignment: 'center',
      resizable: true,
      width: 80,
      label: 'Duration',
    },
  ],
  font: 'Poppins',
  server: 'http://192.168.14.11:4040',
  serverBase64: 'aHR0cDovLzE5Mi4xNjguMTQuMTE6NDA0MA==',
  dynamicBackground: false,
  minimizeToTray: true,
  exitToTray: true,
  windowPosition: { x: 0, y: 0, width: 960, height: 1560 },
  windowMaximize: false,
  highlightOnRowHover: false,
  titleBarStyle: 'windows',
};
