name: Test

# Test only if js/ts files are changed
on:
  push:
    paths:
      - '**.js*'
      - '**.ts*'
  pull_request:
    paths:
      - '**.js*'
      - '**.ts*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.0'

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000 --network-concurrency 1

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc-silent -p ./tsconfig.json --suppress 2702@/node_modules/react-chartjs-2/ 9006@/src/main.dev.js
          yarn test
